task14 | added solution
Jampire/php-tatsiana-areshchanka pull request #12
Opened 2022-06-10 14:50 UTC by TatsiaA

task14 | added solution

2022-06-11 14:22 UTC, Jampire requested changes

2022-06-11 14:22 UTC, Jampire commented on tests/Task14/Task14test.php
> +            $this->assertArrayHasKey($key, $newArr);
This is not enough. You did 2 out of at least 4 tests.
You tested:
- keys were not lost
- key-value pairs are persisted

What you did not test:
- new keys are not added to new array
- array is actually suffled

2022-06-13 07:22 UTC, TatsiaA commented on tests/Task14/Task14test.php
> +            $this->assertArrayHasKey($key, $newArr);
added functions for testing

2022-06-13 09:30 UTC, Jampire requested changes

2022-06-13 09:30 UTC, Jampire commented on tests/Task14/Task14test.php
> +            $arrays_are_not_equal = ($this->stack !== $newArr);
Once again, do not create new variable for such simple calculation and single use. 
Why do you do this check on each iteration, if this check doesn't depend on array elements, but test whole array and result will be the same for each iteration?

2022-06-15 07:14 UTC, merged